### ISSUE TITLE
Add Google+ icon

### ISSUE THREAD

**Issue by luccamordente** [7Ds7/social-iconset#1]
Hi, nice work!

I was almost using your iconset and saw that Google+ icon isn't included.
Do you plan to add it?

Thanks!

**Comment by 7Ds7** [comment]
Hi and thanks :) 

I am currently in vacation mode, will surely add it when I am back in a few days.

**Comment by luccamordente** [comment]
Yay! Nice to know. I hope it will be in time to swap from the iconset I'm using now.

Thanks!

**Comment by 7Ds7** [comment]
Just added the G+ icon to the repo ;)

**Comment by luccamordente** [comment]
Yay! Thanks :)

**Comment by luccamordente** [comment]
Hey, @7Ds7, what is your opinion on making the G+ icon a little bit bigger?
It becomes more visually connected to the others, IMHO.

Look:
![image](https://cloud.githubusercontent.com/assets/106093/17663298/0db919c2-62c2-11e6-91cf-d13c9dd56902.png)

**Comment by 7Ds7** [comment]
I would be ok with that although that is not how the G+ icon is meant to be used according to their guidelines https://developers.google.com/+/images/branding/gplus-icons.zip

**Comment by luccamordente** [comment]
Makes sense. It turns out that what I need is the Google icon, not the Google+ icon. Would you add that too? I'm using for sign in button. And I found these guidelines: https://developers.google.com/identity/branding-guidelines

**Comment by 7Ds7** [comment]
The google sign-in icon/button gets out of the social scope for this repo, also according to those guidelines the icon should not stand only by itself, it should appear next to the action text and always on white background (except when disabled).
I think that for the sign-in part you are better off with their assets https://developers.google.com/identity/images/signin-assets.zip

**Comment by luccamordente** [comment]
> The google sign-in icon/button gets out of the social scope for this repo

That's what I supposed. Thank you, anyway!
